### ISSUE TITLE
Pull request ans branches

### ISSUE THREAD

**Issue by lifeisnice12** [dcblogdev/loginregister#36]
Hi Dave i like to make some liittle modifications in your code.
 - Add  the choice of a case sansitive or not username.

Can you tell me why you have two branches ?
Is the Tutorial branch the developpment branch ?
I see the master is not up to date. 

Thank you for reply
Kind regards

Olivier

**Comment by dcblogdev** [comment]
the tutorial branch is to have a snapshot of what it was originally for the tutorial since this seems popular I have master and tutorial.

This way the master can be changed without making it hard for anyone following the tutorial.

**Comment by lifeisnice12** [comment]
OK I understand. 
Is it possible to submit a pull request if I suggest to add the choice to work with case sensitive or not usernames ? Actually the username is case sensitive as you know.

**Comment by dcblogdev** [comment]
thank you, I've merged this in.
