### ISSUE TITLE
I'm still having issues setting up the email client.

### ISSUE THREAD

**Issue by imadofficial** [dcblogdev/loginregister#39]
I tried setting it up but I recieve nothing:

Here's how I have it setup:

public $From     = 'imadamroug89@gmail.com';
    public $FromName = SITETITLE;
    public $Host     = 'smtp.gmail.com';
    public $Mailer   = 'smtp';
    public $SMTPAuth = true;
    public $Username = 'imadamroug89@gmail.com';
    public $Password = 'email password';
    //public $SMTPSecure = 'tls';
    public $WordWrap = 75;

Is there anything wrong with it?

**Comment by dcblogdev** [comment]
that looks right but your google account may not allow to send the emails: By default, any third-party apps/codes are not allowed to send emails using your Gmail account. And, hence there are few settings which need to be done at your end

have a look at the steps details here https://pepipost.com/tutorials/send-an-email-via-gmail-smtp-server-using-php/

**Comment by imadofficial** [comment]
Well I don't really know what's wrong. It doesn't display any errors on XAMPP. Do you know a tool how to diagnose them?

**Comment by dcblogdev** [comment]
you could try using a third party SMTP service in case its Gmail stopping it from working. Such as https://www.mailgun.com

**Comment by imadofficial** [comment]
I'll give it a try and update you when i'm done

**Comment by imadofficial** [comment]
Wait does outlook work? Or does it have no support?

**Comment by imadofficial** [comment]
I'm starting to wonder, is this Config.php right?

define('DIR','http://imadofficial.gq/');
define('SITEEMAIL','postmaster@sandboxd0983cd95d434beab46b6ceb5439e33b.mailgun.org');
