### ISSUE TITLE
localhost connecting error

### ISSUE THREAD

**Issue by Venushka34** [dcblogdev/loginregister#41]
SQLSTATE[HY000] [1045] Access denied for user 'database username'@'localhost' (using password: YES)
how to fix this error

![bandicam 2020-10-27 10-50-32-767](https://user-images.githubusercontent.com/61352269/97260730-67e70180-1843-11eb-88bd-76581e9667b6.jpg)

**Comment by dcblogdev** [comment]
change the database credentials to match your own. In includes/config.php
