### ISSUE TITLE
Fatal error: Class 'PhpMailer' not found in /var/customers/webs/ni220257_1/classes/phpmailer/mail.php on line 4

### ISSUE THREAD

**Issue by Manuey** [dcblogdev/loginregister#42]
Fatal error: Class 'PhpMailer' not found in /var/customers/webs/ni220257_1/classes/phpmailer/mail.php on line 4

I use Mailtrap as recommended. But I always get this error

lass Mail extends PhpMailer
{
    // Set default variables for all new objects
    public $From     = 'noreply@domain.com';
    public $FromName = SITETITLE;
    public $Host     = 'smtp.mailtrap.io';
    public $Mailer   = 'smtp';
    public $SMTPAuth = true;
    public $Username = '8ebfcbd3a72136';
    public $Password = '*************';
    //public $SMTPSecure = 'tls';
    public $WordWrap = 75;

Thanks for any help!

**Comment by adamf1631** [comment]
This is not built for mailtrap. Standard php mail function.

**Comment by dcblogdev** [comment]
I've upgraded to the latest version of PHPMailer, redownload and try it again.
